### ISSUE TITLE
Criar um projeto em c# console log para implementação da Orientação a Objetos

### ISSUE THREAD

**Issue by alansousa** [leodias/CSharp-OO#1]
Crie um projeto em C# Console para que possam ser implementadas as boas práticas de desenvolvimento orientado a objetos

**Comment by leodias** [comment]
Projeto C# Console criado e nomeado como BoasPraticasOOP.

Como devo proceder para upar o mesmo?

**Comment by leodias** [comment]
Procedimento efetuado.
